### ISSUE TITLE
Transport Layers (TL) not detected - Docker Installation

### ISSUE THREAD

**Issue by VDelv** [alliedvision/VmbPy#24]
Hello,

First thanks for the python package it's really helpful for my actual project.
I am trying to install vmbpy in a Docker container.
I installed Vimba and Vimba X during the image building,

```
# Vimba Installation
RUN tar -xf Vimba64_v6.0_Linux.tar -C /opt \
    && rm Vimba64_v6.0_Linux.tar \
    && mkdir -p /etc/udev/rules.d \
    && cd /opt/Vimba_6_0/VimbaUSBTL/ \
    && ./Install.sh \
    && cd /opt/Vimba_6_0/VimbaGigETL \
    && ./Install.sh \
```

```
# Vimba X Installation
RUN tar -xf VimbaX_2023-4.tar -C /opt \
    && rm VimbaX_2023-4.tar \
    && cd /opt/VimbaX_2023-4/cti/ \
    && ./VimbaGigETL_Install.sh \
    && ./VimbaUSBTL_Install.sh \
```

And then do the python package installation with the wheels available on the GitHub: `vmbpy-1.0.4-py3-none-any.whl`.

But when I try to import `Camera` from `vmbpy` I have the error related to TL not detected:
```
VmbSystemError: No TL detected. Please verify VimbaX installation.
```
Is there something I am missing during the installation? 

Thanks in advance!

**Comment by Teresa-AlliedVision** [comment]
When installed in opt, you need sudo for access rights to access the transport layer. Otherwise you can use a different installation folder in home.
