### ISSUE TITLE
VmbCError(<VmbError.InternalFault: -1>)

### ISSUE THREAD

**Issue by julienenpc** [alliedvision/VmbPy#25]
Hello,
My camera works in Vimba X. Python worked to run a Gx3300 ethernet camera. However when i use a usb camera it doesn't work : i have the **VmbCError(<VmbError.InternalFault: -1>) error.**

If i do the "list-camera.py" from example i get : 
_//////////////////////////////////
/// VmbPy List Cameras Example ///
//////////////////////////////////

Cameras found: 1
/// Camera Name   : Allied Vision 1800 U-1620m
/// Model Name    : 1800 U-1620m
/// Camera ID     : DEV_1AB22C024B86
/// Serial Number : 0381Y
/// Interface ID  : VimbaUSBInterface_0x0_

However, when i try a grab with example code or a simple code i have the error  : 

_from vmbpy import *

with VmbSystem.get_instance () as vmb:
    cams = vmb.get_all_cameras ()
    with cams [0] as cam:
        arr = cam.get_frame ()_

As adviced i tried to reinstalled the whl (python -m pip --force-reinstall  vmbpy-1.0.2-py3-none-any.whl), the installation worked but still the same issue.
Do you have any idea to make it work?

**Comment by Teresa-AlliedVision** [comment]
This seems to be a known issue with Firmware 10. Please update to the latest version, currently 13, from our website:
https://www.alliedvision.com/de/support/firmware-downloads/
Feel free to reopen the issue or put in a support request through our webiste form, if it issue persists.

The rest of the setup and the behaviour in Vimba Viewer look good, so I don't expect other issues.
