### ISSUE TITLE
Can't use frame buffer

### ISSUE THREAD

**Issue by pieterdepiet** [alliedvision/VmbPy#29]
I am using an Prosilica GT 5120 NIR, and need to capture two images shortly after each other. Faster than the GigE cable can transport one image (200ms~). Between a set of two images there is enough time for the images to be delivered (1s).
All Prosilica GT cameras have an internal frame buffer, that would be able to store images before sending them.
My model has enough capacity for 4 images.

https://cdn.alliedvision.com/fileadmin/content/documents/products/cameras/various/features/GigE_Features_Reference.pdf

In the features reference I found that you could use AcquisitionMode = Recorder to save images to internal buffer to achieve higher framerate than the bandwidth allows.
My configuration is: 
cam.AcquisitionMode.set('Recorder')
cam.StreamFrameRateConstrain.set(False)
cam.AcquisitionFrameCount.set(2)
cam.RecorderPreEventCount.set(1)
cam.TriggerSelector.set('FrameStart')
cam.TriggerMode.set('On')
cam.TriggerSource.set('Line2')
cam.TriggerActivation.set('RisingEdge')
and for AcquisitionRecord I have triggermode = on, triggersource = Line2, Activation=FallingEdge

An ESP32 waits for an event and then gives rising edge, waits 30 ms, gives falling edge, waits again 20ms and new rising edge.
But always one of the triggers gets ignored. I have to wait for two ESP32 triggers to get two images. I can not manage to get a burst framerate higher than 4.5fps.

I also tried AcquisitionMode = Multiframe, with StreamFrameRateConstrain = False and temporarily StreamHoldEnable = On.
I let the ESP32 give triggers 100fps, but when I disabled StreamHoldEnable again, 
But then I also can't get the framerate higher than 4.5fps.
I tried setting AcquisitionFrameRateLimit higher, but it is unwritable. I also tried setting AcquisitionFrameRateAbs to a higher value, but it could not be higher than 4.5fps.

The firmware version is 00.01.54.20443

It seems like the frame buffer is not usable at all. Or StreamFrameRateConstrain.set(False) doesn't work.
Is the frame buffer useable at all? And if so, how could I use it?

**Comment by Teresa-AlliedVision** [comment]
Hello Pieter,
in this case, it is not a Python issue, but some in depth support regarding the recorder feature, FPS and triggering. For that, please put in a support request through our website form and include the serial number there (on the housing, marked with S/N).
