### ISSUE TITLE
What do "buffer_count" and "allocation_mode" do under the hood?

### ISSUE THREAD

**Issue by Brenden-Morales** [alliedvision/VmbPy#30]
I was having a hell of a time getting images to display smoothly and without tearing on a raspberry pi 5. I changed 

`cam.start_streaming(handler=self.frame_handler, buffer_count=1, allocation_mode=AllocationMode.AnnounceFrame)`
to
`cam.start_streaming(handler=self.frame_handler, buffer_count=3, allocation_mode=AllocationMode.AnnounceFrame)`

and that fixed my issue, awesome!

I want to know _why_ though. Is there a detailed explanation of how buffer_count works? I mean, I can guess but I'd really like to know the actual details.

Additionally, what does allocation_mode do? Is it worth messing with that to try and improve performance as well?

**Comment by Teresa-AlliedVision** [comment]
The default value used for buffers is usually 7-10 frames, but for high FPS or multi camera systems, 20 or 30 might be applicable, depending on your system.
To explain:
The frame buffer in your program does as it says. It buffers the images, that are given from the transport layer to the application layer (your program). When all the spots in the queue are full, the images that newly arrive wil be discarded until a spot is freed in the queue. 
That is why the frame callback/frame received method/frame observer alsways needs to requeue the frame, after the processing on it is done at the end.
You can see why this could lead to issues, if the frame queue is just one frame big. That means the frame processing needs to be done before the next frame has arrived. But both the program and the interface do not always work at the same speed continously, so these small fluctuations need to be buffered.
This behaviour compunds, when you have multi camera systems, where the scheduling the system does for receiving the data from the cameras and processing the frames in multiple threads has even more impact.
Plus, with Python there is even more fluctuations in processing times and delays.

It is possible to use the so calles _alloc and announce_ mode to allocate buffers, which can be more efficient.
https://docs.alliedvision.com/Vimba_X/Vimba_X_DeveloperGuide/pythonAPIManual.html#acquiring-images
The Python API is a wrapper for the C-API, so if you want to know more about what it does in the background, you can look at the C-API or the general API manual.
https://docs.alliedvision.com/Vimba_X/Vimba_X_DeveloperGuide/sdkManual.html#buffer-management

**Comment by Brenden-Morales** [comment]
Ahhhh thanks so much!
