### ISSUE TITLE
How to get aperture value?

### ISSUE THREAD

**Issue by AytajHsnv** [alliedvision/VmbPy#31]
Hello,

I wanna know that is there way to get exact aperture value from camera? 

Thank you so much in advance.

**Comment by Teresa-AlliedVision** [comment]
Hello, this is not relevant to the Python API. Please open a support ticket through our website or your camera distributor, if applicable. Make sure to include the serial number and camera model in the support request, as there are only selected models, that would support Iris control.
https://www.alliedvision.com/en/about-us/contact-us/technical-support-repair-/-rma/
