### ISSUE TITLE
Cameras are not visible

### ISSUE THREAD

**Issue by eli-osherovich** [alliedvision/VmbPy#32]
I am trying to use `harvesters` with Vimba TL and cannot get the cameras' list. 
Using other TL implementations (cti files) the code below prints all the cameras connected to the network. However, VimbaGigETCL produces an empty list. 

Is Vimba limited to AlliedVision cameras only?

```
from harvesters.core import Harvester
h = Harvester()
h.add_file('/tmp/VimbaGigETL.cti')
h.update()
h.device_info_list # it is empty
```

**Comment by Teresa-AlliedVision** [comment]
Hello, this repo is only for the VmbPy API. Please open a support ticket through our website or your distributor, if the camera was not bought from Allied Vision directly.
https://www.alliedvision.com/en/about-us/contact-us/technical-support-repair-/-rma/
