### ISSUE TITLE
Capture frame using IP address

### ISSUE THREAD

**Issue by Masrur02** [alliedvision/VmbPy#33]
How can imges be captured using IP address of a camera rather than the camera ID? I mean what is the python code for doing this?

**Comment by Teresa-AlliedVision** [comment]
Please use the function ge_camera_by_id(), see the function reference for more information:
https://docs.alliedvision.com/Vimba_X/VmbPy_Function_Reference/VmbSystem.html#vmbpy.VmbSystem.__Impl.get_camera_by_id
