### ISSUE TITLE
Please verify VimbaX installation

### ISSUE THREAD

**Issue by hibi11000** [alliedvision/VmbPy#36]
I'm trying to install the python API for Vimba X on my Raspberry Pi 5 with Raspian. 
As i tried to run my python program, i got this error message:

Exception has occurred: VmbSystemError
Failed to load library 'X/VimbaX_2023-4/api/lib/libVmbC.so'. Please verify VimbaX installation.
OSError: X/VimbaX_2023-4/api/lib/libVmbC.so: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

  File "/home/pi/Desktop/Visual Studio /camera.py", line 1, in <module>
    from vmbpy import *
vmbpy.error.VmbSystemError: Failed to load library 'X/VimbaX_2023-4/api/lib/libVmbC.so'. Please verify VimbaX installation.

**Comment by Teresa-AlliedVision** [comment]
Hi, in what directory is the VimbaX API installed/saved and what version did you download?

**Comment by hibi11000** [comment]
I dont know how, but i managed to fix it.
