### ISSUE TITLE
Synchronous acquisition repeatedly saves same frames randomly, pixelformat invalid (0) when using as_opencv_image

### ISSUE THREAD

**Issue by pikhan** [alliedvision/VmbPy#38]
Cannot find a solution to this anywhere and I've tried all that I can. I am trying to do synchronous camera acquisition for a much broader program. Typically it works, however, randomly it will start to save the same image over and over instead of the new one. It always starts copying the second image it saves never any others. Restarting the program/unplugging and re-plugging in the camera has been the current workaround. The error is due to the Frame.Status being incomplete and the pixel format not being valid (0 instead of PixelFormat.Mono8) 

Here is the current cameraIO.py class where I define a VimbaCam() class to be used in the main program, the function that is primarily used outside this class is capture_image and the actual acquisition and setting of current_frame (where the errors are reported to be occurring) is in thread_stream. You can kind of see what I've tried and what doesn't work here.

The camera is a recently bought Allied Vision Alvium 1800 U-2560m. We replaced another same model camera with a newer one and are still getting this issue. We used to implement a simple delay to deal with this issue but over time had to increase the time, possibly due to camera overheating. Now the setup has an attached fan and the issue still persists albeit we no longer have as long of a delay implemented. 

The issue is similar to https://github.com/alliedvision/VimbaPython/issues/62 and https://github.com/alliedvision/VimbaPython/issues/115. I've tried playing around with the devicelinkthroughput and usbfs buffer etc. but it doesn't fix anything unfortunately. The computer its running on is an Ubuntu 24.04.1 LTS and I am currently using vmbpy 1.0.4 (vmbc 1.0.5). The USB connection is on a superspeed usb3.0 port.

import copy
import queue
import threading
from typing import Optional
import cv2
import numpy as np
from vmbpy import *
import time

def create_dummy_frame() -> np.ndarray:
    cv_frame = np.zeros((50, 640, 1), np.uint8)
    cv_frame[:] = 0
    cv2.putText(cv_frame, 'No Stream available. Please connect a Camera.', org=(30, 30),
                fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL, fontScale=1, color=255, thickness=1)
    return cv_frame

class VimbaCam:

    def __init__(self, device_id=0):
        # Variables
        self.current_frame = None
        self.device = None
        self.device_id = device_id
        self.vimba_handle = VmbSystem.get_instance().__enter__()
        self.is_streaming = False
        self.scale_window = 4
        self.stream_thread = threading.Thread(target=self.thread_stream, daemon=True)

        self.open()

    def close(self):
        if self.device is not None:
            if self.is_streaming:
                self.stop_stream()
                time.sleep(1)
            self.device.__exit__(None, None, None)
            self.vimba_handle.__exit__(None, None, None)

    def open(self):
        cams = self.vimba_handle.get_all_cameras()
        if not cams:
            print('no cams!')
        else:
            self.device = cams[self.device_id].__enter__()

        self.set_defaults()
        self.start_stream()

    # def start_stream(self):
    #     if self.device is not None:
    #         self.is_streaming = True
    #         self.stream_thread.start()
    #         time.sleep(1)
    #
    # def reset_stream(self):
    #     if self.device is not None:
    #         print("Resetting camera stream...")
    #         self.stop_stream()
    #         time.sleep(1)  # Allow the camera some time to reset
    #         self.start_stream()
    # def start_stream(self):
    #     if self.device is not None:
    #         print("Starting stream...")
    #         self.is_streaming = True
    #         self.stream_thread = threading.Thread(target=self.thread_stream,
    #                                               daemon=True)  # Create a new thread instance
    #         self.stream_thread.start()  # Start the new thread
    #         time.sleep(1)
    #         print("Stream started.")
    # def start_stream(self):
    #     if self.device is not None and not self.is_streaming:
    #         print("Starting stream...")
    #         self.is_streaming = True
    #         self.stream_thread = threading.Thread(target=self.thread_stream, daemon=True)  # Create a new thread instance
    #         self.stream_thread.start()  # Start the new thread
    #         time.sleep(1)
    #         print("Stream started.")
    #
    # def reset_stream(self):
    #     if self.device is not None:
    #         print("Resetting camera stream...")
    #         self.stop_stream()
    #         self.current_frame = None  # Clear the current frame before resetting
    #         time.sleep(1)  # Allow the camera some time to reset
    #         self.start_stream()  # Create and start a new thread
    #         print("Stream reset complete.")
    def start_stream(self):
        if self.device is not None and not self.is_streaming:
            print("Starting stream...")
            self.is_streaming = True

            # Create a new thread to handle the frame streaming
            self.stream_thread = threading.Thread(target=self.thread_stream, daemon=True)
            self.stream_thread.start()
            time.sleep(1)
            print("Stream started.")

    def reset_stream(self):
        if self.device is not None:
            print("Resetting camera stream...")
            self.stop_stream()
            self.current_frame = None  # Clear the current frame before resetting
            time.sleep(1)  # Allow the camera some time to reset

            # Reopen the device (context) and restart the stream properly
            with self.device:
                # Nothing else to do here since stream is handled in thread_stream()
                pass

            self.start_stream()  # Create and start a new thread
            print("Stream reset complete.")

    def thread_stream(self):
        with self.device:  # Ensure we're in the context of the camera
            while self.is_streaming:
                try:
                    current_frame = self.device.get_frame(timeout_ms=5000)
                    try:
                        if current_frame.get_pixel_format() is not PixelFormat.Mono8:
                            print("Setting Pixel Format, currently:")
                            print(current_frame.get_pixel_format())
                            current_frame.convert_pixel_format(target_fmt=PixelFormat.Mono8)
                    except ValueError as e:
                        print(e)
                        print("Not a valid pixel format, attempting to get new frame") #can't manually set pixelformat as it calls the get_pixel_format function and raises a value error...
                        self.device.queue_frame(current_frame)
                        time.sleep(0.01)
                        current_frame = self.device.get_frame(
                            timeout_ms=10000)  # doesnt really help either..
                except IndexError:
                    print("Stream not initialized correctly. Resetting stream...")
                    self.reset_stream()
                    time.sleep(1) # some additional time to set
                    return  # Exit the thread after resetting

                retry = 0
                while current_frame.get_status() != FrameStatus.Complete:
                    if not self.is_streaming:
                        return  # Exit the thread when streaming is stopped
                    if retry > 1:
                        print("RESETTING CAMERA STREAM \n") #doesn't work it just crashes the program as detecting that this thread closes calls the rest of the program outside this to stop...
                        self.reset_stream()
                        return  # Exit the current thread after resetting

                    print("CURRENT FRAME STATUS: \n")
                    print(current_frame.get_status())
                    print("CURRENT FRAME BUFFER: \n")
                    print(current_frame.get_buffer())
                    print("CURRENT FRAME BUFFER SIZE: \n")
                    print(current_frame.get_buffer_size())
                    print("CURRENT CAMERA PIXEL FORMAT: \n")
                    print(self.device.get_pixel_format())
                    print("CURRENT FRAME INCOMPLETE, WAITING 1s, resetting frame in between")
                    self.device.queue_frame(current_frame)
                    time.sleep(0.50) # Need to adjust based on overheating
                    current_frame = self.device.get_frame(timeout_ms=10000, allocation_mode=AllocationMode.AllocAndAnnounceFrame) #previously tried changing allocation mode but default is good
                    self.current_frame = current_frame.as_opencv_image()
                    h, w, _ = current_frame.shape
                    self.current_frame = current_frame.reshape((h, w))
                    time.sleep(0.50) #these sleep calls may not even be doing anything
                    retry += 1
                if not self.is_streaming:
                    return  # Exit the thread when streaming is stopped
                current_frame = current_frame.as_opencv_image()
                h, w, _ = current_frame.shape
                self.current_frame = current_frame.reshape((h, w))
            #self.stream_thread = threading.Thread(target=self.thread_stream, daemon=True)

    # def stop_stream(self):
    #     if self.device is not None:
    #         self.is_streaming = False

    def stop_stream(self):
        if self.device is not None:
            print("Stopping stream...")
            self.is_streaming = False  # Set flag to False to stop the loop
            if threading.current_thread() is not self.stream_thread:  # Only join if calling from a different thread
                if self.stream_thread.is_alive():
                    self.stream_thread.join()  # Wait for the thread to finish if it’s still running
            print("Stream stopped.")

    def live_video(self):
        if self.device is not None:
            window_name = "Allied Vision"
            h, w = self.current_frame.shape
            w = int(w / self.scale_window)
            h = int(h / self.scale_window)
            cv2.namedWindow(window_name, cv2.WINDOW_NORMAL)
            cv2.resizeWindow(window_name, w, h)
            while 1:
                cv2.imshow(window_name, self.current_frame)
                cv2.waitKey(1)
                if cv2.getWindowProperty(window_name, cv2.WND_PROP_VISIBLE) < 1:
                    break
            cv2.destroyAllWindows()

    def set_defaults(self):
        self.set_nearest_value('Height', 4608)
        self.set_nearest_value('Width', 5328)
        self.device.ExposureTime.set(4855.798)
        self.device.ExposureAuto.set('Off')
        self.device.Gain.set(0)
        self.device.GainAuto.set('Off')
        self.device.set_pixel_format(PixelFormat.Mono8)
        self.device.BlackLevel.set(0)
        self.device.AcquisitionMode.set('Continuous')
        self.device.Gamma.set(1.00)
        self.device.get_feature_by_name('DeviceLinkThroughputLimit').set(360905933)

    def set_nearest_value(self, feat_name: str, feat_value: int):
        with self.device:
            feat = self.device.get_feature_by_name(feat_name)
        try:
            feat.set(feat_value)
        except VmbFeatureError:
            min_, max_ = feat.get_range()
            inc = feat.get_increment()
            if feat_value <= min_:
                val = min_
            elif feat_value >= max_:
                val = max_
            else:
                val = (((feat_value - min_) // inc) * inc) + min_
            feat.set(val)
            msg = f'Camera {self.device.get_id()}: Failed to set Feature {feat_name} to {feat_value}. Using nearest valid value {val}.'
            Log.get_instance().info(msg)

    def capture_image(self, save_path: Optional[str] = None, max_wait_time: float = 2.0) -> np.ndarray:
        # Wait for a valid current_frame within the timeout period
        start_time = time.time()
        while self.current_frame is None and (time.time() - start_time) < max_wait_time:
            print("Waiting for new frame...")
            time.sleep(0.1)  # Small wait time to avoid busy waiting

        if self.current_frame is not None:
            image = self.current_frame
            if save_path:
                try:
                    cv2.imwrite(save_path, image)
                    print(f"Image saved as {save_path}")
                except Exception as e:
                    print(f"Failed to save image: {e}")
            return image
        else:
            # If no frame was captured within the wait time, return a dummy frame
            print(f"No valid frame captured within {max_wait_time} seconds.")
            return create_dummy_frame()

**Comment by Teresa-AlliedVision** [comment]
Hi, if I read your code correctly, when the frame status is incomplete you wait in the while loop and put the same frame object into the queue again and again?
Incomplete frames are missing at least one packet, but at this point they are already in the application layer, so the transport layer does not add any data to them anymore. 
Basically, for USB, if the host is too slow in getting the data packets from the camera, the internal ring buffer in the camera is overwritten with the rest of the frame. The camera then lets the host know and the frame is marked incomplete or, if a lot of packets are missing, is dropped.

To solve this:

- troubleshoot  your USB connection, e.g. using Bandwidth manager statistics to test
- the User Guide and the USB application notes have more information on how to set up and manage USB Vision systems 
https://www.alliedvision.com/en/support/technical-documentation/alvium-usb-documentation/
- do not work with incomplete frames, **the frame status should be used to discard the ones that are not complete**
- If you are unable to solve your USB connection issues, please open a support case through the website, since this is not connected to the Python API
https://www.alliedvision.com/en/about-us/contact-us/technical-support-repair-/-rma/

**Comment by pikhan** [comment]
Initially, I was not doing anything at all with queue_frame() and still had the exact same issue. Initially, we would just have a time.sleep() inside the while loop if the Frame.Status was incomplete. I did troubleshoot the USB connection and varying the usbfs buffer, devicelinkthroughput, etc. did not make any difference. I wanted to use queue_frame as a way to discard the incomplete frame and to then synchronously re-grab a new one. How would I do this correctly?

**Comment by Teresa-AlliedVision** [comment]
The frame observer is stuck in the loop `while current_frame.get_status() != FrameStatus.Complete:`. That is why no new frame can be processed.
You are indefinetely waiting for the frame to become complete, but it never will. Once the frame is in the application layer and it is incomplete, it will stay incomplete.
Just put the frame back into the frame queue once and retrigger the frame.

Have a look at the examples, the best practice is to check if the frame is complete and if it is complete, you can work with it. If you want to, you can read out incomplete status to retrigger the farme or for statistics.

If decreasing the DeviceLinkThroughputLimit did not change anything, then you need to decrease it further or use a dedicated USB card.
Have you looked at the application notes and User Guide?
For further troubleshooting rearding your USB connection, please open a support ticket.

**Comment by pikhan** [comment]
Could you kindly show how to correctly put the frame back into the frame queue once and retrigger the frame?
I have tried a number of things and based on debug output I do know that I am not stuck in the loop. In my newest attempt to fix this, you can see that there is an explicit retry counter. I have played with the commented code in and out. All cause the same repeating frame error.

    def thread_stream(self):
        with self.device:  # Ensure we're in the context of the camera
            while self.is_streaming:
                try:
                    # Attempt to get a frame
                    current_frame = self.device.get_frame(timeout_ms=5000)

                    # Check frame status before proceeding
                    if current_frame.get_status() != FrameStatus.Complete:
                        print("Incomplete frame received, NOT requeuing...")
                        #self.device.queue_frame(current_frame)
                        #time.sleep(0.01)  # Short delay to prevent overloading
                        retry_count = 0
                        # Retry to get a complete frame
                        while retry_count < 5 and current_frame.get_status() != FrameStatus.Complete:
                            if not self.is_streaming:
                                return  # Exit if streaming stops
                            if retry_count < 1:
                                print(f"Retry {retry_count}: Incomplete frame, retrying with different method first...")
                                for frame in self.device.get_frame_generator(limit=1, timeout_ms=500):
                                    #self.device.queue_frame(self.current_frame)
                                    current_frame = frame
                                retry_count += 1
                            elif retry_count > 1:
                                print(f"Retry {retry_count}: Incomplete frame, retrying with original method and more time...")
                                #self.device.queue_frame(self.current_frame)
                                #self.device.queue_frame(current_frame)  # Requeue the current frame
                                current_frame = self.device.get_frame(timeout_ms=10000)
                                retry_count += 1
                            elif retry_count > 2:
                                print(f"Retry {retry_count}: Incomplete frame, retyring with different method and more time...")
                                #self.device.queue_frame(self.current_frame)
                                #self.device.queue_frame(current_frame)  # Requeue the current frame
                                for frame in self.device.get_frame_generator(limit=1, timeout_ms=10000):
                                    current_frame = frame
                                retry_count += 1
                        if current_frame.get_status() != FrameStatus.Complete:
                            print("Frame still incomplete after retries. Resetting stream...")
                            self.reset_stream()  # Reset the camera stream if retries fail
                            return

                    # Now handle the pixel format conversion
                    try:
                        if current_frame.get_pixel_format() is not PixelFormat.Mono8:
                            print(f"Current pixel format: {current_frame.get_pixel_format()}, converting to Mono8")
                            current_frame.convert_pixel_format(PixelFormat.Mono8)
                    except ValueError as e:
                        print(f"Error converting pixel format: {e}")
                        self.device.queue_frame(current_frame)
                        continue

                    # # Convert the frame to OpenCV image
                    # current_frame = current_frame.as_opencv_image()
                    # h, w, _ = current_frame.shape
                    # self.current_frame = current_frame.reshape((h, w))
                    self.current_frame = current_frame

                except Exception as e:
                    print(f"Error occurred: {e}")
                    self.reset_stream()
                    return  # Exit after resetting

                # If streaming stops, exit
                if not self.is_streaming:
                    return
          
I also tried checking for incomplete status in the function that actually captures the image and is called. Changes here also did not make a difference.

    def capture_image(self, save_path: Optional[str] = None, max_wait_time: float = 15.0) -> np.ndarray:
        # Wait for a valid current_frame within the timeout period
        start_time = time.time()
        while (self.current_frame is None or self.current_frame.get_status() != FrameStatus.Complete) and (time.time() - start_time) < max_wait_time:
            print("Waiting for new frame...")
            time.sleep(2)  # Small wait time to avoid busy waiting

        if self.current_frame is not None:
            # Convert the frame to OpenCV image
            image = self.current_frame.as_opencv_image()
            h, w, _ = image.shape
            image = image.reshape((h, w))
            #image = self.current_frame
            if save_path:
                try:
                    cv2.imwrite(save_path, image)
                    print(f"Image saved as {save_path}")
                except Exception as e:
                    print(f"Failed to save image: {e}")
            return image
        else:
            # If no frame was captured within the wait time, return a dummy frame
            print(f"No valid frame captured within {max_wait_time} seconds.")
            return create_dummy_frame()
            
The error is intermittent and seems to occur after closing and re-opening the camera object and is "solved" the same way. I am not sure why this causes an incomplete frame (always the second image it takes) sometimes and I am not sure how to properly deal with. I would sincerely appreciate your help. Thank you!
