### ISSUE TITLE
Drop link to developer guide in readme?

### ISSUE THREAD

**Issue by ivalaginja** [alliedvision/VmbPy#40]
Just as a suggestion, would you consider dropping the link to the [Vimba X developer guide](https://docs.alliedvision.com/Vimba_X/Vimba_X_DeveloperGuide/index.html) into this repo's readme? It is always really hard to navigate through the full alliedvision.com website to find it as it's really burried.

Alternatively, since this is the repo specifically for the Python API VmbPy, you could link to the [Python API documentation](https://docs.alliedvision.com/Vimba_X/Vimba_X_DeveloperGuide/pythonAPIManual.html)?

**Comment by Teresa-AlliedVision** [comment]
This and some other updates to the information of the readme are planned for the next release. Thanks for the suggestion.
